services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/task
      JWT_ACCESS_SECRET: changeme
      JWT_REFRESH_SECRET: changeme2
      COOKIE_DOMAIN: localhost
      API_PUBLIC_URL: http://api:3001
      DS_PUBLIC_URL: http://onlyoffice
      DS_JWT_SECRET: supersecret
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - api_uploads:/app/uploads

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      VITE_DS_URL: http://localhost:8082
    depends_on:
      - api
    ports:
      - "5174:5173"   # host:container (frontend va fi accesibil la http://localhost:5174)

  onlyoffice:
    image: onlyoffice/documentserver:latest
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=supersecret
      - JWT_HEADER=Authorization
    ports:
      - "8082:80"
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
    depends_on:
      - api

volumes:
  db_data:
  api_uploads:
  onlyoffice_data:
